server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/Andrei Cazaceanu/Documents/GitHub Maria/sma-workspace/sma-configuration-service/src/main/resources/config/licensingservice
