version: '2'
services:
  #  database:
  #    image: postgres
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      POSTGRES_USER: "postgres"
  #      POSTGRES_PASSWORD: "p0stgr@s"
  #      POSTGRES_DB: "eagle_eye_local"
  eureka:
    image: mariamihai/sma-eureka-service:latest
    ports:
      - 8761:8761
  config-service:
    image: mariamihai/sma-configuration-service:latest
    ports:
      - 8888:8888
    depends_on:
      - eureka
    env_file:
      - local.env
    environment:
      SPRING_PROFILES_ACTIVE: "native, local-docker"
      SERVICE_URL_DEFAULT_ZONE: http://eureka:8761/eureka/
  licensing-service:
    image: mariamihai/sma-licensing-service:latest
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config-service
#      - database
    environment:
      SPRING_PROFILES_ACTIVE: "local-docker"
      SERVICE_URL_DEFAULT_ZONE: http://eureka:8761/eureka/
    env_file:
      - local.env
